START TRANSACTION;

    INSERT INTO `kb_section` VALUES 
        (1, 'Form Interrogatories - General'),
        (2, 'Form Interrogatories - Employment'),
        (3, 'Special Interrogatories'),
        (4, 'Requests for Admission'),
        (5, 'Requests for Production of Documents'),
        (6, 'Commonly used but invalid objections');

-- For filling the kb_to_kb_section relationship, use /([(]\d+,).*(,"[\d,]+"[)])/ to /$1$2/

    INSERT INTO `kb` VALUES 
(01,0,"Ambiguous","Objection, ambiguous. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.","Objection, ambiguous. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.\n\r\n\rUse Notes\n\rThis is only a valid objection if interrogatory is wholly unintelligible. An interrogatory must be answered if “the nature of the information sought is apparent.” Deyo v Kilbourne (1978) 84 CA3d 771, 783.","1,2,3"),
(02,0,"Attorney-client and work product privilege","Objection, this interrogatory improperly seeks information protected by the attorney-client and/or attorney work product privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.240, subd. (b).","Objection, this interrogatory improperly seeks information protected by the attorney-client and/or attorney work product privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.240, subd. (b).","1,2,3"),
(03,0,"Blanket objection to entire set of interrogatories","Objection, responding party objects to this entire set of interrogatories. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.","Objection, responding party objects to this entire set of interrogatories. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.\n\r\n\rUse Notes\n\rValid only if every interrogatory is objectionable. Judge should grant motion to compel as to all unobjectionable interrogatories. West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 418.","1,2,3"),
(04,0,"Confidential","Objection, confidential. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.240, subd. (b).","Objection, confidential. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.240, subd. (b).\n\r\n\rUse Notes\n\rThis is only a valid objection if an applicable confidentiality privilege is claimed. Code Civ.Proc., § 2030.240, subd. (b).","1,2,3"),
(05,0,"Continuing","Objection, continuing interrogatory. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.060, subd. (g).","Objection, continuing interrogatory. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.060, subd. (g).\n\r\n\rUse Notes\n\r“An interrogatory may not be made a continuing one so as to impose on the party responding to it a duty to supplement an answer to it that was initially correct and complete with later acquired information.” Code Civ.Proc., § 2030.060, subd. (g).","1,2,3"),
(06,0,"Cumulative","Objection, this interrogatory is cumulative. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2019.030, subd. (a)(1).","Objection, this interrogatory is cumulative. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2019.030, subd. (a)(1).\n\r\n\rUse Notes\n\rValid only if discovery is unreasonably cumulative or duplicative. Code Civ.Proc., § 2019.030, subd. (a)(1).","1,2,3"),
(07,0,"[seeks] Documents","Objection, this interrogatory improperly seeks documents. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.","Objection, this interrogatory improperly seeks documents. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.\n\r\n\rUse Notes\n\r“No provision relating to interrogatories authorizes compelling production of a document or thing.” Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.","1,2,3"),
(08,0,"Equally available to propounding party","Objection, the information sought is equally available to propounding party. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.220, subd. (c) and Alpine Mut. Water Co. v Superior Court (1968) 259 CA2d 45, 54.","Objection, the information sought is equally available to propounding party. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.220, subd. (c) and Alpine Mut. Water Co. v Superior Court (1968) 259 CA2d 45, 54.\n\r\n\rUse Notes\n\rNote that Judicial Council forms, i.e. form interrogatories, are presumptively valid. Gov. Code, § 68511; Code Civ.Proc., § 2033.710.","1,2"),
(09,0,"Form","Objection, the form of the interrogatory is improper. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.060.","Objection, the form of the interrogatory is improper. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.060.\n\r\n\rUse Notes\n\rHowever, Alpine Mut. Water Co. v Superior Court (1968) 259 CA2d 45 is limited to publicly available documents.","1,2"),
(10,0,"Irrelevant to the subject matter","Objection, this interrogatory is irrelevant to the subject matter of this case. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2017.010.","Objection, this interrogatory is irrelevant to the subject matter of this case. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2017.010.","1,2,3"),
(11,0,"Legal reasoning or theory","Objection, this interrogatory improperly intrudes into the party's legal reasoning or theory. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.010, subd. (b) and Sav-On Drugs, Inc. v. Superior Court (1975) 15 Cal.3d 1.","Objection, this interrogatory improperly intrudes into the party's legal reasoning or theory. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.010, subd. (b) and Sav-On Drugs, Inc. v. Superior Court (1975) 15 Cal.3d 1.","1,2,3"),
(12,0,"Oppressive","Objection, this interrogatory is oppressive. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 417.","Objection, this interrogatory is oppressive. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 417.\n\r\n\rUse Notes\n\r“To support an objection of oppression there must be some showing either of an intent to create an unreasonable burden or that the ultimate effect of the burden is incommensurate with the result sought.” West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 417.","1,2,3"),
(13,0,"Privacy","Objection, this interrogatory improperly invades privacy rights protected by art I, § 1 of the California Constitution and the First Amendment to U.S. Constitution. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.","Objection, this interrogatory improperly invades privacy rights protected by art I, § 1 of the California Constitution and the First Amendment to U.S. Constitution. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.\n\r\n\rUse Notes\n\rSome courts used to require the party seeking private information to justify the need for it. Recently, however, the California Supreme Court reversed the burden. Now, “the party asserting a privacy right must establish a legally protected privacy interest, an objectively reasonable expectation of privacy in the given circumstances, and a threatened intrusion that is serious.” Williams v. Superior Court (2017) 3 Cal.5th 531, 552.","1,2,3"),
(14,0,"Public record","Objection, this interrogatory improperly seeks information in the public record. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.220, subd. (c).","Objection, this interrogatory improperly seeks information in the public record. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.220, subd. (c).","1,2,3"),
(15,0,"Trade Secrets","Objection, this interrogatory improperly seeks information protected by the trade secrets privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.240, subd. (b).","Objection, this interrogatory improperly seeks information protected by the trade secrets privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.240, subd. (b).\n\r\n\rUse Notes\n\rThis applies only if you've asserted a trade secrets privilege. Code Civ.Proc., § 2030.240, subd. (b).","1,2,3"),
(16,0,"Unduly burdensome","Objection, this interrogatory is unduly burdensome. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.","Objection, this interrogatory is unduly burdensome. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.\n\r\n\rUse Notes\n\r“The objection based upon burden must be sustained by evidence showing the quantum of work required.” West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 417.","1,2,3"),

(17,0,"Equally available to propounding party","Objection, the information sought is equally available to propounding party. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.220, subd. (c) and Alpine Mut. Water Co. v Superior Court (1968) 259 CA2d 45, 54.","Objection, the information sought is equally available to propounding party. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.220, subd. (c) and Alpine Mut. Water Co. v Superior Court (1968) 259 CA2d 45, 54.\n\r\n\rUse Notes\n\rAlpine Mut. Water Co. v Superior Court (1968) 259 CA2d 45 is limited to publicly available documents.","3"),
(18,0,"Form","Objection, the form of the interrogatory is improper. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.060.","Objection, the form of the interrogatory is improper. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2030.060.","3"),
(19,0,"Compound, conjunctive, or disjunctive","Objection, this interrogatory is compound, conjunctive, or disjunctive. Code Civ.Proc., § 2030.060, subd. (f).","Objection, this interrogatory is compound, conjunctive, or disjunctive. Code Civ.Proc., § 2030.060, subd. (f).","3"),
(20,0,"Exceeds 35-interrogatory limit","Objection, this interrogatory exceeds the 35-interrogatory limit. Code Civ.Proc., § 2030.030, subd. (c).","Objection, this interrogatory exceeds the 35-interrogatory limit. Code Civ.Proc., § 2030.030, subd. (c).\n\r\n\rUse Notes\n\rNot valid where Interrogatories include a Declaration for Additional Discovery. Code Civ.Proc., § 2030.030, subd. (c).","3"),
(21,0,"Subparts","Objection, this interrogatory improperly contains subparts. Code Civ.Proc., §§ 2030.060, subd. (f), 2033.710.","Objection, this interrogatory improperly contains subparts. Code Civ.Proc., §§ 2030.060, subd. (f), 2033.710.\n\r\n\rUse Notes\n\rThe prohibition on subparts does not appear to prohibit their use in definitions.","3"),

(22,0,"Ambiguous","Objection, ambiguous.","Objection, ambiguous.\n\r\n\rUse Notes\n\rAmbiguity is only a sufficient ground for refusal to answer if the request is so ambiguous that the responding party cannot in good faith frame an intelligent reply. Cembrook v. Superior Court In and For City and County of San Francisco (1961) 56 Cal.2d 423, 428.","4"),
(23,0,"Attorney-client and work product privilege","Objection, this request improperly seeks information protected by the attorney-client and/or attorney work product privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.230, subd. (b).","Objection, this request improperly seeks information protected by the attorney-client and/or attorney work product privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.230, subd. (b).","4"),
(24,0,"Blanket objection to entire set of requests","Objection, responding party objects to this entire set of requests. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30.","Objection, responding party objects to this entire set of requests. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30.\n\r\n\rUse Notes\n\rValid only if each request is objectionable. Judge should grant motion to compel as to all unobjectionable requests. West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 418.","4"),
(25,0,"Combined discovery methods","Objection, this request improperly combines different discovery methods. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.060, subd. (h).","Objection, this request improperly combines different discovery methods. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.060, subd. (h).","4"),
(26,0,"Confidential","Objection, confidential. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.230, subd. (b).","Objection, confidential. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.230, subd. (b).\n\r\n\rUse Notes\n\rThis is only a valid objection if an applicable confidentiality privilege is claimed.","4"),
(27,0,"Documents not attached","Objection, documents not attached. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.060, subd. (g).","Objection, documents not attached. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.060, subd. (g).\n\r\n\rUse Notes\n\rOnly a valid objection for a request for admission of the genuineness of a document.","4"),
(28,0,"Exceeds 35-requests limit","Objection, this request exceeds the 35-request limit. Code Civ.Proc., § 2033.030, subd. (b).","Objection, this request exceeds the 35-request limit. Code Civ.Proc., § 2033.030, subd. (b).\n\r\n\rUse Notes\n\rNot valid where requests include a Declaration for Additional Discovery. Code Civ.Proc., § 2033.030, subd. (b).","4"),
(29,0,"Form","Objection, the form of the request is improper. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.060.","Objection, the form of the request is improper. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.060.","4"),
(30,0,"Irrelevant to the subject matter","Objection, this request is irrelevant to the subject matter of this case. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2017.010.","Objection, this request is irrelevant to the subject matter of this case. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2017.010.","4"),
(31,0,"Oppressive","Objection, this request is oppressive. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30.","Objection, this request is oppressive. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30.\n\r\n\rUse Notes\n\r“To support an objection of oppression there must be some showing either of an intent to create an unreasonable burden or that the ultimate effect of the burden is incommensurate with the result sought.” West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 417.","4"),
(32,0,"Privacy","Objection, this request improperly invades privacy rights protected by art I, § 1 of the California Constitution and the First Amendment to U.S. Constitution. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30.","Objection, this request improperly invades privacy rights protected by art I, § 1 of the California Constitution and the First Amendment to U.S. Constitution. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30.\n\r\n\rUse Notes\n\rSome courts used to require the party seeking private information to justify the need for it. Recently, however, the California Supreme Court reversed the burden. Now, “the party asserting a privacy right must establish a legally protected privacy interest, an objectively reasonable expectation of privacy in the given circumstances, and a threatened intrusion that is serious.” Williams v. Superior Court (2017) 3 Cal.5th 531, 552.","4"),
(33,0,"Subparts","Objection, this request improperly contains subparts. Code Civ.Proc., §§ 2033.060, subd. (f), 2033.710.","Objection, this request improperly contains subparts. Code Civ.Proc., §§ 2033.060, subd. (f), 2033.710.\n\r\n\rUse Notes\n\rThe prohibition on subparts does not appear to prohibit their use in definitions.","4"),
(34,0,"Trade Secrets","Objection, this request improperly seeks information protected by the trade secrets privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.230, subd. (b).","Objection, this request improperly seeks information protected by the trade secrets privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30, citing Code Civ.Proc., § 2033.230, subd. (b).\n\r\n\rUse Notes\n\rThis applies only if you've asserted a trade secrets privilege. Code Civ.Proc., § 2030.240, subd. (b).","4"),
(35,0,"Unduly burdensome","Objection, this request is unduly burdensome. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 22.30.","Objection, this request is unduly burdensome. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.\n\r\n\rUse Notes\n\r“The objection based upon burden must be sustained by evidence showing the quantum of work required.” West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 417.","4"),

(36,0,"Ambiguous","Objection, ambiguous. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.","Objection, ambiguous. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.\n\r\n\rUse Notes\n\rThis is only a valid objection if ambiguity precludes an intelligent reply. Cembrook v Superior Court (1961) 56 C2d 423, 430.","5"),
(37,0,"Blanket objection to entire set of requests","Objection, responding party objects to this entire set of requests. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.","Objection, responding party objects to this entire set of requests. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.\n\r\n\rUse Notes\n\rValid only if each request is objectionable. Judge should grant motion to compel as to all unobjectionable interrogatories. West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 418.","5"),
(38,0,"Confidential","Objection, confidential. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.240, subd. (b).","Objection, confidential. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.240, subd. (b).\n\r\n\rUse Notes\n\rThis is only a valid objection if an applicable confidentiality privilege is claimed. Code Civ.Proc., § 2031.240, subd. (b).","5"),
(39,0,"Equally available to propounding party","Objection, the information sought is equally available to propounding party. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.230.","Objection, the information sought is equally available to propounding party. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.230.\n\r\n\rUse Notes\n\rValid only if demand would require respondent to make more than a “reasonable inquiry.” Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.","5"),
(40,0,"Form","Objection, the form of the request is improper. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.030.","Objection, the form of the request is improper. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.030.","5"),
(41,0,"Irrelevant to the subject matter","Objection, this request is irrelevant to the subject matter of this case. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2017.010.","Objection, this request is irrelevant to the subject matter of this case. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2017.010.","5"),
(42,0,"Oppressive","Objection, this request is oppressive. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Mead Reinsurance Co. v Superior Court (1986) 188 CA3d 313, 321.","Objection, this request is oppressive. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Mead Reinsurance Co. v Superior Court (1986) 188 CA3d 313, 321.\n\r\n\rUse Notes\n\r“To support an objection of oppression there must be some showing either of an intent to create an unreasonable burden or that the ultimate effect of the burden is incommensurate with the result sought.” West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 417.","5"),
(43,0,"[Insufficient] particularity","Objection, this request is insufficiently particularized. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.030, subd. (c)(1).","Objection, this request is insufficiently particularized. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.030, subd. (c)(1).","5"),
(44,0,"[Unreasonable] place","Objection, this request specifies an unreasonable place for performing the activity. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.030, subd. (c)(3).","Objection, this request specifies an unreasonable place for performing the activity. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.030, subd. (c)(3).","5"),
(45,0,"Privacy","Objection, this request improperly invades privacy rights protected by art I, § 1 of the California Constitution and the First Amendment to U.S. Constitution. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.","Objection, this request improperly invades privacy rights protected by art I, § 1 of the California Constitution and the First Amendment to U.S. Constitution. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.\n\r\n\rUse Notes\n\rSome courts used to require the party seeking private information to justify the need for it. Recently, however, the California Supreme Court reversed the burden. Now, “the party asserting a privacy right must establish a legally protected privacy interest, an objectively reasonable expectation of privacy in the given circumstances, and a threatened intrusion that is serious.” Williams v. Superior Court (2017) 3 Cal.5th 531, 552.","5"),
(46,0,"[Unreasonable] time","Objection, this request specifies an unreasonable time for performing the activity. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.030, subd. (c)(2).","Objection, this request specifies an unreasonable time for performing the activity. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.030, subd. (c)(2).","5"),
(47,0,"Trade Secrets","Objection, this request improperly seeks information protected by the trade secrets privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.240, subd. (b)(2).","Objection, this request improperly seeks information protected by the trade secrets privilege. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30, citing Code Civ.Proc., § 2031.240, subd. (b)(2).","5"),
(48,0,"Unduly burdensome","Objection, this request is unduly burdensome. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.","Objection, this request is unduly burdensome. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.\n\r\n\rUse Notes\n\r“The objection based upon burden must be sustained by evidence showing the quantum of work required.” West Pico Furniture Co. of Los Angeles v. Superior Court In and For Los Angeles County (1961) 56 Cal.2d 407, 417.","5"),
(49,0,"Unintelligible or vague","Objection, unintelligible or vague. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.","Objection, unintelligible or vague. Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 19.30.\n\r\n\rUse Notes\n\rThis is only a valid objection if ambiguity precludes an intelligent reply. Cembrook v Superior Court (1961) 56 C2d 423, 430.","5"),

        (50, 1, 'Answer is known to propounding party',     NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing <i>Alpine Mut. Water Co. v Superior Court</i> (1968) 259 CA2d 45, 54.',""),
        (51, 1, 'Asked and answered',                       NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing <i>Coy v Superior Court</i> (1962) 58 C2d 210, 218.',""),
        (52, 1, 'Assumes facts not in evidence',            NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing <i>West Pico Furniture Co. v Superior Court</i> (1961) 56 C2d 407, 421.',""),
        (53, 1, 'Burdensome',                               NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35. However, “unduly burdensome” is valid. <i>Id.</i>, citing Code Civ.Proc., § 2017.020, subd. (a).',""),
        (54, 1, 'Calls for a contention',                   NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35 citing Code Civ.Proc., § 2030.010, subd. (b) and <i>Grace v Mansourian</i> (2015) 240 CA4th 523, 530.',""),
        (55, 1, 'Calls for a legal conclusion',             NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35 citing Code Civ.Proc., § 2017.010 and <i>Greyhound Corp. v Superior Court</i> (1961) 56 C2d 355, 392.',""),
        (56, 1, 'Calls for a legal opinion',                NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35 citing Code Civ.Proc., § 2030.010, subd. (b).',""),
        (57, 1, 'Calls for speculation*',                   NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.\r\n\r\n* Not approved but not expressly disapproved.',""),
        (58, 1, 'Complex',                                  NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35. However, if the complexity imposes an “undue burden” that objection is valid.',""),
        (59, 1, 'Compound, conjunctive, or disjunctive',    NULL, 'Valid only for Special Interrogatories. Code Civ.Proc., § 2030.060, subd. (f).',""),
        (60, 1, 'Controversial',                            NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing <i>Cembrook v. Superior Court In and For City and County of San Francisco</i> (1961) 56 Cal.2d 423, 429.',""),
        (61, 1, 'Document speaks for itself*',              NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35. This objection is only used at trial. <i>Northern California Water Assn. v. State Water Resources Control Bd.</i> (2018) 20 Cal.App.5th 1204, 1223, Fn 18.\r\n\r\n* Not approved but not expressly disapproved.',""),
        (62, 1, 'Exceeds 35-requests limit',                NULL, 'Only applies to Special Interrogatories. Code Civ.Proc., § 2030.030, subd. (c).',""),
        (63, 1, 'Fishing expedition',                       NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing <i>Greyhound Corp. v. Superior Court In and For Merced County</i> (1961) 56 Cal.2d 355, 385-386 [“There is nothing improper about a fishing expedition, per se.”]',""),
        (64, 1, 'Hearsay',                                  NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2017.010, subd. (c) and <i>Greyhound Corp. v. Superior Court In and For Merced County</i> (1961) 56 Cal.2d 355, 392.',""),
        (65, 1, 'Invalid hypothetical*',                    NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.\r\n\r\n* Not approved but not expressly disapproved.',""),
        (66, 1, 'Irrelevant to the issues',                 NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2017.010.',""),
        (67, 1, 'Known to the propounding party',           NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.',""),
        (68, 1, 'Lacks or insufficient foundation',         NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2017.010.',""),
        (69, 1, 'Not applicable',                           NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.',""),
        (70, 1, 'Overbroad',                                NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35, citing Code Civ.Proc., § 2017.010.',""),
        (71, 1, 'Shotgun',                                  NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.',""),
        (72, 1, 'Vague',                                    NULL, 'Cal. Judges Benchbook Civ. Proc. Discovery (August 2019), § 18.35.',"");

    INSERT INTO `kb_kb_section` VALUES 
        (01,1),
        (01,2),
        (01,3),
        (02,1),
        (02,2),
        (02,3),
        (03,1),
        (03,2),
        (03,3),
        (04,1),
        (04,2),
        (04,3),
        (05,1),
        (05,2),
        (05,3),
        (06,1),
        (06,2),
        (06,3),
        (07,1),
        (07,2),
        (07,3),
        (08,1),
        (08,2),
        (09,1),
        (09,2),
        (10,1),
        (10,2),
        (10,3),
        (11,1),
        (11,2),
        (11,3),
        (12,1),
        (12,2),
        (12,3),
        (13,1),
        (13,2),
        (13,3),
        (14,1),
        (14,2),
        (14,3),
        (15,1),
        (15,2),
        (15,3),
        (16,1),
        (16,2),
        (16,3),
        (17,3),
        (18,3),
        (19,3),
        (20,3),
        (21,3),
        (22,4),
        (23,4),
        (24,4),
        (25,4),
        (26,4),
        (27,4),
        (28,4),
        (29,4),
        (30,4),
        (31,4),
        (32,4),
        (33,4),
        (34,4),
        (35,4),
        (36,5),
        (37,5),
        (38,5),
        (39,5),
        (40,5),
        (41,5),
        (42,5),
        (43,5),
        (44,5),
        (45,5),
        (46,5),
        (47,5),
        (48,5),
        (49,5);

COMMIT;
