
    INSERT INTO `kb` VALUES 
(400,2,"ACCOMMODATION","ACCOMMODATION means a modification or adjustment to the workplace that enables the employee to perform the essential functions of the job.","",""),
(401,2,"DISABILITY","A DISABILITY is a physical or mental condition that limits a major life activity; it may be actual or perceived by the employer.","",""),
(402,2,"DISCIPLINE or DISCIPLINARY ACTION","DISCIPLINE or DISCIPLINARY ACTION refer to actions including but not limited to, a warning or admonishment, whether oral or written, any reduction in rank, seniority, job duties, schedule changes, title, benefits, or pay, suspension, or termination.","",""),
(403,2,"HARASS, HARASSING or HARASSMENT","HARASS, HARASSING or HARASSMENT refer to verbal conduct such as making epithets, derogatory comments or slurs, romantic overtures, sexual comments and/or jokes, and prying into one’s personal affairs; physical conduct such as unwanted touching, rubbing against someone, assault, and physical interference with movement or work; and visual conduct such as derogatory cartoons, drawings or posters, and lewd gestures or leering.","",""),
(404,2,"IDENTITY, IDENTIFY, or IDENTIFICATION","IDENTITY, IDENTIFY, or IDENTIFICATION means to provide the person’s full name, last-known residential address, last-known residential phone number, and if the person is currently employed by AEGIS. ","",""),
(405,2,"LIST","LIST means to state the date of the statement, contents of the statement, IDENTITY of everyone who witnessed the statement, and whether the plaintiff was present. ","",""),
(406,2,"NEGATIVE","NEGATIVE means focused on what is bad or lacking.","",""),
(407,2,"POLICIES","POLICIES mean the way YOU interact with and discipline YOUR employees, including but not limited to policies, procedures, handbooks, guidelines, and rules.","",""),
(408,2,"PROPER MEAL BREAKS","PROPER MEAL BREAKS refer to meal breaks at least 30 minutes long; uninterrupted by any work; where the employee was free to leave YOUR premises; and which began no later than the end of the employee’s fifth hour of work.","",""),
(409,2,"PROPER REST BREAKS","PROPER REST BREAKS refer to rest breaks at least 10 minutes long; uninterrupted by any work; occurring every 4 hours, or major fraction thereof, of work; and YOU made a good faith effort to provide the break in the middle of the work period.","",""),
(410,2,"RELATED TO","RELATED TO means referencing or referring to in any way, whether expressly or impliedly.","",""),
(411,2,"UNDUE HARDSHIP","UNDUE HARDSHIP means an action requiring significant difficulty or expense, when considered in light of (1) The nature and cost of the accommodation; (2) The anticipated financial resources involved in the provision of the accommodation, the number of employees at the facility where the employee worked, and the effect on expenses and resources or the impact of the accommodation upon the operation of the facility; (3) YOUR overall financial resources, the number of employees affected, and the number, type, and location of the facility where INCLAN worked; (4) The type of operations of YOUR workforce; and (5) The geographic separateness or administrative or fiscal relationship of the facility where the employee worked.","",""),
(412,2,"YOU and YOUR","YOU and YOUR refer to respondent or any of YOUR agents, representatives, affiliated entities or anyone acting or whom YOU know or believe is purporting to act on YOUR behalf or who has acted or whom YOU know or believe is purporting to act on YOUR behalf.","","");

    INSERT INTO `kb_kb_section` VALUES 
        (400,3),
        (401,3),
        (402,3),
        (403,3),
        (404,3),
        (405,3),
        (406,3),
        (407,3),
        (408,3),
        (409,3),
        (410,3),
        (411,3),
        (412,3),

        (400,4),
        (401,4),
        (402,4),
        (403,4),
        (404,4),
        (405,4),
        (406,4),
        (407,4),
        (408,4),
        (409,4),
        (410,4),
        (411,4),
        (412,4),

        (400,5),
        (401,5),
        (402,5),
        (403,5),
        (404,5),
        (405,5),
        (406,5),
        (407,5),
        (408,5),
        (409,5),
        (410,5),
        (411,5),
        (412,5);
