START TRANSACTION;
  SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

  ALTER TABLE `responses` 
    ADD COLUMN `payment_intent_id` VARCHAR(45) NULL DEFAULT NULL;
  
  SET SQL_MODE=@OLD_SQL_MODE;
COMMIT;